<%@ page import="java.util.List" %>
<%@ page import="com.example.demo.model.Orders" %>
<%@ page import="com.example.demo.model.OrderdProducts" %>
<%@ page import="java.util.Set" %>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
         pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
    <%--<%@ include file="includes/style.jsp" %>--%>
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
</head>
<body>
<%@ include file="includes/adnavbar.jsp" %><br/><br/>
    <div class="container">
        <div class="row">
            <div class="col"></div>
            <div class="col-8">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">Order ID</th>
                        <th scope="col">Order Date</th>
                        <th scope="col">Customer Id</th>
                        <th scope="col">Order Amount</th>
                        <th scope="col">No of products</th>
                    </tr>
                    </thead>
                    <tbody>
                        <% List<Orders> oList=(List<Orders>)request.getAttribute("rList");
                        Double amount=0.0;
                        for(Orders o:oList){
                        amount+=o.getAmount();
                        %>
                        <tr>
                            <td><a href='/order?id=<%=o.getId()%>&uid=<%=o.getCustomerId()%>'><%= o.getId()%></a></td>
                            <td><%= o.getDate()%></td>
                            <td><%= o.getCustomerId()%></td>
                            <td><%= o.getAmount()%></td>
                            <td><%= o.getOrderdProducts().size()%></td>
                        </tr>
                        <%}%>
                    </tbody>
                </table>
            </div>
            <div class="col"></div>
        </div>
        <div class="row">
            <div class="col"></div>
            <div class="col">
                <div class="alert alert-primary" role="alert">
                    Total Revenue Generated $<%=amount %>
                </div>
            </div>
            <div class="col"></div>
        </div>
        <div class="row">
            <div class="col"></div>
            <div class="col-8">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">Product Id</th>
                        <th scope="col">Product Name</th>
                        <th scope="col">Product Price</th>
                        <th scope="col">Category</th>
                        <th scope="col">Order Id</th>
                    </tr>
                    </thead>
                    <tbody>
                <% Double colthing=0.0;
                    for(Orders o:oList) {
                        Set<OrderdProducts> op = o.getOrderdProducts();
                        for (OrderdProducts p : op) {
                            if (p.getCategory().equals("Clothing")) {
                                int id=o.getId();
                                colthing += p.getPrice();
                                out.println("<tr><td>" + p.getPid() + "</td>");
                                out.println("<td>" + p.getName() + "</td>");
                                out.println("<td>" + p.getPrice() + "</td>");
                                out.println("<td>" + p.getCategory() + "</td>");
                                out.println("<td>" + id + "</td></tr>");
                            }
                        }
                    }%>
                    </tbody>
                </table>
            </div>
            <div class="col"></div>
        </div>
        <div class="row">
            <div class="col"></div>
            <div class="col">
                <div class="alert alert-primary" role="alert">
                    Total Revenue Generated by Clothing category $<%=colthing %>
                </div>
            </div>
            <div class="col"></div>
        </div>
        <div class="row">
            <div class="col"></div>
            <div class="col-8">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">Product Id</th>
                        <th scope="col">Product Name</th>
                        <th scope="col">Product Price</th>
                        <th scope="col">Category</th>
                        <th scope="col">Order Id</th>
                    </tr>
                    </thead>
                    <tbody>
                    <% Double accessories=0.0;
                        for(Orders o:oList) {
                            Set<OrderdProducts> op = o.getOrderdProducts();
                            for (OrderdProducts p : op) {
                                if (p.getCategory().equals("Accessories")) {
                                    int id=o.getId();
                                    accessories	 += p.getPrice();
                                    out.println("<tr><td>" + p.getPid() + "</td>");
                                    out.println("<td>" + p.getName() + "</td>");
                                    out.println("<td>" + p.getPrice() + "</td>");
                                    out.println("<td>" + p.getCategory() + "</td>");
                                    out.println("<td>" + id + "</td></tr>");
                                }
                            }
                        }%>
                    </tbody>
                </table>
            </div>
            <div class="col"></div>
        </div>
        <div class="row">
            <div class="col"></div>
            <div class="col">
                <div class="alert alert-primary" role="alert">
                    Total Revenue Generated by Accessories	 category $<%=accessories	 %>
                </div>
            </div>
            <div class="col"></div>
        </div>
        <div class="row">
            <div class="col"></div>
            <div class="col-8">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">Product Id</th>
                        <th scope="col">Product Name</th>
                        <th scope="col">Product Price</th>
                        <th scope="col">Category</th>
                        <th scope="col">Order Id</th>
                    </tr>
                    </thead>
                    <tbody>
                    <% Double merch=0.0;
                        for(Orders o:oList) {
                            Set<OrderdProducts> op = o.getOrderdProducts();
                            for (OrderdProducts p : op) {
                                if (p.getCategory().equals("Merchandise")) {
                                    int id=o.getId();
                                    merch	 += p.getPrice();
                                    out.println("<tr><td>" + p.getPid() + "</td>");
                                    out.println("<td>" + p.getName() + "</td>");
                                    out.println("<td>" + p.getPrice() + "</td>");
                                    out.println("<td>" + p.getCategory() + "</td>");
                                    out.println("<td>" + id + "</td></tr>");
                                }
                            }
                        }%>
                    </tbody>
                </table>
            </div>
            <div class="col"></div>
        </div>
        <div class="row">
            <div class="col"></div>
            <div class="col">
                <div class="alert alert-primary" role="alert">
                    Total Revenue Generated by Merchandise	 category $<%=merch	 %>
                </div>
            </div>
            <div class="col"></div>
        </div>
    </div>
<%@ include file="includes/scripts.jsp" %>
</body>
</html>